# =========================
# = spring configuration
# =========================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dashboard
#    url: jdbc:mysql://mysql:3306/cryptoManager
#    url: jdbc:mariadb://localhost:3306/cryptoManager
    username: dashboard
    password: dashboard
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
# =========================
# = HTTPS Configuration
# =========================
server:
  port: 8443
  ssl:
    enabled: true
    key-alias: tomcat-localhost
    key-password: dashboard
    key-store: classpath:keystore.jks
    key-store-provider: SUN
    key-store-type: JKS
    key-store-password: dashboard
  error:
    include-stacktrace: always
# =========================
# = Domoticz configuration
# =========================
domoticz:
  server:
    protocol: https
    host: 192.168.178.3
    port: 443
    user: admin
    pass: admin